sudo: required
language: python
addons:
  chrome: stable
python:
  "3.9"
install:
  pip install tox
script:
  tox

before_install:
  - wget https://chromedriver.storage.googleapis.com/98.0.4758.80/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$(pwd)

