sudo: required
language: python
addons:
  - chrome: stable
python:
  - "3.6"
install:
  - pip install tox
script:
  - tox

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start
